function [apriori_cov] = compute_apriori_covariance(propagated_states,apriori_state)
    removed_expectation = propagated_states-apriori_state;
    apriori_cov = SigmaPointConstants.W_c_0 * ...
        (removed_expectation(:,1))*(removed_expectation(:,1))' + ...
        SigmaPointConstants.W_i * ...
        (removed_expectation(:, 2:end))*(removed_expectation(:, 2:end))';
end

