function [state] = generate_initial_est_state()
    state = [SigmaPointConstants.initial_x SigmaPointConstants.initial_y ...
        SigmaPointConstants.initial_theta 0 0 0 0 0 0 ...
        0 0 0 0 SigmaPointConstants.est_imu_bias SigmaPointConstants.est_rangefinder_bias]';
end
