function [cov_mat] = generate_initial_covariance_matrix()
    cov_mat = diag([SigmaPointConstants.initial_pos_std^2 SigmaPointConstants.initial_pos_std^2 ...
        SigmaPointConstants.initial_ang_std^2 ...
        SigmaPointConstants.initial_vel_std^2 SigmaPointConstants.initial_vel_std^2 ...
        SigmaPointConstants.initial_angvel_std^2 ...
        SigmaPointConstants.initial_accel_std^2 SigmaPointConstants.initial_accel_std^2 ...
        SigmaPointConstants.initial_angaccel_std^2 ...
        SigmaPointConstants.est_wheel_noise_std^2 SigmaPointConstants.est_wheel_noise_std^2 ...
        SigmaPointConstants.est_encoder_noise_std^2 SigmaPointConstants.est_encoder_noise_std^2 ...
        SigmaPointConstants.est_accel_noise_std^2 SigmaPointConstants.est_accel_noise_std^2 ...
        SigmaPointConstants.est_gyro_noise_std^2 ...
        SigmaPointConstants.est_rangefinder_noise_std^2 ...
        SigmaPointConstants.est_rangefinder_noise_std^2 ...
        SigmaPointConstants.est_rangefinder_noise_std^2]);
end

