function [state] = generate_initial_true_state()
    state = [SigmaPointConstants.initial_x SigmaPointConstants.initial_y ...
        SigmaPointConstants.initial_theta 0 0 0 0 0 0 ...
        0 0 0 0 SigmaPointConstants.imu_bias SigmaPointConstants.rangefinder_bias]';
end
