function torque = torque_curve(wheel_vel, input)
    torque = max(-1,min(1,input))*RobotConstants.wheel_stall_torque*...
        basic_torque_curve(sign(input)*wheel_vel/RobotConstants.wheel_top_angspeed)-...
        sign(wheel_vel)*RobotConstants.internal_wheel_friction_torque;
end